[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    bodmer/TFT_eSPI @ ^2.5.31
    tamctec/TAMC_GT911 @ ^1.0.2
    https://github.com/ayushsharma82/AsyncElegantOTA.git#v2.2.7
    esphome/ESPAsyncWebServer-esphome @ ^3.0.0
    esphome/AsyncTCP-esphome @ ^2.0.1

build_flags =
    -D MQTT_MAX_PACKET_SIZE=4096 
    -D CORE_DEBUG_LEVEL=0
    -I src/pages

extra_scripts = pre:increment_version.py